// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Node struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pubkey               *PubKey  `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Ipaddresses          [][]byte `protobuf:"bytes,3,rep,name=ipaddresses,proto3" json:"ipaddresses,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Lastactivity         int64    `protobuf:"varint,5,opt,name=lastactivity,proto3" json:"lastactivity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Node) GetPubkey() *PubKey {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *Node) GetIpaddresses() [][]byte {
	if m != nil {
		return m.Ipaddresses
	}
	return nil
}

func (m *Node) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Node) GetLastactivity() int64 {
	if m != nil {
		return m.Lastactivity
	}
	return 0
}

func init() {
	proto.RegisterType((*Node)(nil), "protocol.Node")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8d, 0x4d, 0x0a, 0xc2, 0x30,
	0x14, 0x84, 0x49, 0xff, 0x90, 0xd7, 0x20, 0xf2, 0x56, 0xc1, 0x55, 0xe8, 0x2a, 0xab, 0x2e, 0xf4,
	0x18, 0x82, 0x48, 0x6e, 0xd0, 0x36, 0x6f, 0x11, 0x2c, 0xbe, 0xd0, 0xa4, 0x42, 0xaf, 0xe2, 0x69,
	0x85, 0x56, 0x41, 0x57, 0x33, 0x7c, 0x33, 0xcc, 0x00, 0x3c, 0xd8, 0x51, 0x1b, 0x26, 0x4e, 0x8c,
	0xbb, 0x55, 0x06, 0x1e, 0x8f, 0x32, 0xcc, 0xfd, 0x9d, 0x96, 0x8d, 0x37, 0x2f, 0x01, 0xc5, 0x95,
	0x1d, 0xe1, 0x1e, 0x32, 0xef, 0x94, 0xd0, 0xc2, 0x48, 0x9b, 0x79, 0x87, 0x06, 0xaa, 0xad, 0xa8,
	0x32, 0x2d, 0x4c, 0x7d, 0x3a, 0xb4, 0xdf, 0x85, 0xf6, 0x36, 0xf7, 0x17, 0x5a, 0xec, 0x27, 0x47,
	0x0d, 0xb5, 0x0f, 0x9d, 0x73, 0x13, 0xc5, 0x48, 0x51, 0xe5, 0x3a, 0x37, 0xd2, 0xfe, 0x22, 0x44,
	0x28, 0x02, 0x4f, 0x49, 0x15, 0x5a, 0x98, 0xd2, 0xae, 0x1e, 0x1b, 0x90, 0x63, 0x17, 0x53, 0x37,
	0x24, 0xff, 0xf4, 0x69, 0x51, 0xa5, 0x16, 0x26, 0xb7, 0x7f, 0xac, 0xaf, 0xd6, 0xcb, 0xf3, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0x0b, 0x7f, 0xca, 0xb5, 0xc9, 0x00, 0x00, 0x00,
}
