// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeting.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GreetingRequest struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Pubkey               *PubKey  `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingRequest) Reset()         { *m = GreetingRequest{} }
func (m *GreetingRequest) String() string { return proto.CompactTextString(m) }
func (*GreetingRequest) ProtoMessage()    {}
func (*GreetingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acac03ccd168a87, []int{0}
}

func (m *GreetingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingRequest.Unmarshal(m, b)
}
func (m *GreetingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingRequest.Marshal(b, m, deterministic)
}
func (m *GreetingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingRequest.Merge(m, src)
}
func (m *GreetingRequest) XXX_Size() int {
	return xxx_messageInfo_GreetingRequest.Size(m)
}
func (m *GreetingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingRequest proto.InternalMessageInfo

func (m *GreetingRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GreetingRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *GreetingRequest) GetPubkey() *PubKey {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

type GreetingResponse struct {
	Ipaddresses          []byte   `protobuf:"bytes,1,opt,name=ipaddresses,proto3" json:"ipaddresses,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Visible              bool     `protobuf:"varint,3,opt,name=visible,proto3" json:"visible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingResponse) Reset()         { *m = GreetingResponse{} }
func (m *GreetingResponse) String() string { return proto.CompactTextString(m) }
func (*GreetingResponse) ProtoMessage()    {}
func (*GreetingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6acac03ccd168a87, []int{1}
}

func (m *GreetingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingResponse.Unmarshal(m, b)
}
func (m *GreetingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingResponse.Marshal(b, m, deterministic)
}
func (m *GreetingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingResponse.Merge(m, src)
}
func (m *GreetingResponse) XXX_Size() int {
	return xxx_messageInfo_GreetingResponse.Size(m)
}
func (m *GreetingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingResponse proto.InternalMessageInfo

func (m *GreetingResponse) GetIpaddresses() []byte {
	if m != nil {
		return m.Ipaddresses
	}
	return nil
}

func (m *GreetingResponse) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *GreetingResponse) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func init() {
	proto.RegisterType((*GreetingRequest)(nil), "protocol.GreetingRequest")
	proto.RegisterType((*GreetingResponse)(nil), "protocol.GreetingResponse")
}

func init() { proto.RegisterFile("greeting.proto", fileDescriptor_6acac03ccd168a87) }

var fileDescriptor_6acac03ccd168a87 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x49, 0x29, 0x25, 0xba, 0x56, 0x50, 0xdd, 0x64, 0x32, 0x45, 0x99, 0x32, 0x65, 0x28,
	0x6f, 0x00, 0x03, 0x03, 0x0b, 0x32, 0x12, 0x03, 0x1b, 0x6e, 0x4e, 0x91, 0x45, 0x14, 0x1b, 0x9f,
	0x13, 0x29, 0x6f, 0x8f, 0x70, 0x62, 0x05, 0x55, 0x99, 0xec, 0xfb, 0xee, 0x74, 0xdf, 0x7f, 0x70,
	0xd7, 0x38, 0x22, 0xaf, 0xbb, 0xa6, 0xb2, 0xce, 0x78, 0x83, 0x69, 0x78, 0xce, 0xa6, 0xcd, 0x0e,
	0xb6, 0x57, 0xdf, 0x34, 0x4e, 0xbc, 0xd0, 0x70, 0xff, 0x32, 0x4f, 0x4a, 0xfa, 0xe9, 0x89, 0x3d,
	0x0a, 0xb8, 0x1d, 0xc8, 0xb1, 0x36, 0x9d, 0x48, 0xf2, 0xa4, 0xbc, 0x91, 0xb1, 0x44, 0x84, 0xad,
	0x35, 0xce, 0x8b, 0x4d, 0xc0, 0xe1, 0x8f, 0x25, 0xec, 0xa6, 0x85, 0xe2, 0x3a, 0x4f, 0xca, 0xfd,
	0xe9, 0x58, 0x45, 0x53, 0xf5, 0xd6, 0xab, 0x57, 0x1a, 0xe5, 0xdc, 0x2f, 0x14, 0x1c, 0x17, 0x15,
	0x5b, 0xd3, 0x31, 0x61, 0x0e, 0x7b, 0x6d, 0xbf, 0xea, 0xda, 0x11, 0x33, 0x71, 0xf0, 0x1d, 0xe4,
	0x7f, 0xb4, 0xea, 0xfc, 0x4b, 0xa8, 0x59, 0xab, 0x96, 0x82, 0x34, 0x95, 0xb1, 0x3c, 0x7d, 0x2c,
	0xe7, 0xbc, 0x93, 0x1b, 0xf4, 0x99, 0xf0, 0x19, 0xd2, 0x88, 0xf0, 0x61, 0x09, 0x77, 0x71, 0x75,
	0x96, 0xad, 0xb5, 0xa6, 0x94, 0xc5, 0xd5, 0xd3, 0xf6, 0x73, 0x63, 0x95, 0xda, 0x85, 0x91, 0xc7,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x76, 0x5b, 0xf6, 0x5d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreetingServiceClient is the client API for GreetingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetingServiceClient interface {
	Greeting(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error)
}

type greetingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetingServiceClient(cc grpc.ClientConnInterface) GreetingServiceClient {
	return &greetingServiceClient{cc}
}

func (c *greetingServiceClient) Greeting(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error) {
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, "/protocol.GreetingService/Greeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetingServiceServer is the server API for GreetingService service.
type GreetingServiceServer interface {
	Greeting(context.Context, *GreetingRequest) (*GreetingResponse, error)
}

// UnimplementedGreetingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetingServiceServer struct {
}

func (*UnimplementedGreetingServiceServer) Greeting(ctx context.Context, req *GreetingRequest) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greeting not implemented")
}

func RegisterGreetingServiceServer(s *grpc.Server, srv GreetingServiceServer) {
	s.RegisterService(&_GreetingService_serviceDesc, srv)
}

func _GreetingService_Greeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingServiceServer).Greeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.GreetingService/Greeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingServiceServer).Greeting(ctx, req.(*GreetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreetingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.GreetingService",
	HandlerType: (*GreetingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greeting",
			Handler:    _GreetingService_Greeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeting.proto",
}
